set -g default-terminal "screen-256color"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Rebind prefix to Escape-space
set-option -g prefix `
unbind-key C-b
bind-key ` send-prefix

unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on
set -g mode-keys vi

set -g focus-events on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist sessions after computer reboot
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions every 15 minutes

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Colors
base03="#263238" # background (darker)
base02="#073642" # background
base01="#586e75" # content (darkest)
base00="#657b83" # content
base0="#839496" # content
base1="#ffffff" # content (lightest)
yellow="#ffcb6b"
orange="#f78c6c"
red="#ff5370"
magenta="#d33682"
violet="#bb80b3"
blue="#82aaff"
cyan="#89ddff"
green="#c3e88d"

# Status bar
set -g status-position bottom
set -g status-interval 1
set -g status-left-length 60
set -g status-left " #[bold]#S "
set -g status-right-length 140
set -g status-style fg=$base1,bg=$base03
set -g status-right " #(uptime | cut -f 4-5 -d ' ' | cut -f 1 -d ',') "
set -ag status-right "#(top -l 1 | grep -E '^CPU' | sed 's/.*://')"
set -ag status-right "🔋 #(pmset -g batt | tail -1 | awk '{print $3}' | tr -d ';') "
set -ag status-right "🕒 %r "
set -ag status-right "🗓️  %a %d"

# active/inactive windows
set -g window-status-style fg=$base00,bg=$base03
set -g window-status-format ' #I #W '
set -g window-status-current-style fg=$base02,bg=$yellow
set -g window-status-current-format ' #I #W '

# active/inactive panes
setw -g pane-border-style fg=$base01,bg=$base02
setw -g pane-active-border-style fg=$yellow,bg=black
setw -g window-style fg=$base00,bg=$base03
setw -g window-active-style fg=$base1,bg=$base03

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin"
run '~/.tmux/plugins/tpm/tpm'
